// GENERATED FILE — DO NOT EDIT.
// Regenerate with `dart run ffigen` after the C ABI header changes.
// ignore_for_file: type=lint, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Low-level FFI bindings for libyse_c.dll (do not use directly).
class YseBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  YseBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  YseBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> version() {
    return _version();
  }

  late final _versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'yse_version',
      );
  late final _version = _versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> last_error() {
    return _last_error();
  }

  late final _last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'yse_last_error',
      );
  late final _last_error = _last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void clear_last_error() {
    return _clear_last_error();
  }

  late final _clear_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('yse_clear_last_error');
  late final _clear_last_error = _clear_last_errorPtr
      .asFunction<void Function()>();

  /// Borrowed singleton pointer — never destroy.
  ffi.Pointer<YseSystem> system_get() {
    return _system_get();
  }

  late final _system_getPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseSystem> Function()>>(
        'yse_system_get',
      );
  late final _system_get = _system_getPtr
      .asFunction<ffi.Pointer<YseSystem> Function()>();

  /// Lifecycle.
  YseStatus system_init(ffi.Pointer<YseSystem> sys) {
    return YseStatus.fromValue(_system_init(sys));
  }

  late final _system_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<YseSystem>)>
      >('yse_system_init');
  late final _system_init = _system_initPtr
      .asFunction<int Function(ffi.Pointer<YseSystem>)>();

  YseStatus system_init_offline(ffi.Pointer<YseSystem> sys) {
    return YseStatus.fromValue(_system_init_offline(sys));
  }

  late final _system_init_offlinePtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<YseSystem>)>
      >('yse_system_init_offline');
  late final _system_init_offline = _system_init_offlinePtr
      .asFunction<int Function(ffi.Pointer<YseSystem>)>();

  void system_render_offline(ffi.Pointer<YseSystem> sys, int blocks) {
    return _system_render_offline(sys, blocks);
  }

  late final _system_render_offlinePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>, ffi.Int)>
      >('yse_system_render_offline');
  late final _system_render_offline = _system_render_offlinePtr
      .asFunction<void Function(ffi.Pointer<YseSystem>, int)>();

  void system_update(ffi.Pointer<YseSystem> sys) {
    return _system_update(sys);
  }

  late final _system_updatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_update',
      );
  late final _system_update = _system_updatePtr
      .asFunction<void Function(ffi.Pointer<YseSystem>)>();

  void system_close(ffi.Pointer<YseSystem> sys) {
    return _system_close(sys);
  }

  late final _system_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_close',
      );
  late final _system_close = _system_closePtr
      .asFunction<void Function(ffi.Pointer<YseSystem>)>();

  void system_pause(ffi.Pointer<YseSystem> sys) {
    return _system_pause(sys);
  }

  late final _system_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_pause',
      );
  late final _system_pause = _system_pausePtr
      .asFunction<void Function(ffi.Pointer<YseSystem>)>();

  void system_resume(ffi.Pointer<YseSystem> sys) {
    return _system_resume(sys);
  }

  late final _system_resumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_resume',
      );
  late final _system_resume = _system_resumePtr
      .asFunction<void Function(ffi.Pointer<YseSystem>)>();

  /// Diagnostics.
  int system_missed_callbacks(ffi.Pointer<YseSystem> sys) {
    return _system_missed_callbacks(sys);
  }

  late final _system_missed_callbacksPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_missed_callbacks',
      );
  late final _system_missed_callbacks = _system_missed_callbacksPtr
      .asFunction<int Function(ffi.Pointer<YseSystem>)>();

  double system_cpu_load(ffi.Pointer<YseSystem> sys) {
    return _system_cpu_load(sys);
  }

  late final _system_cpu_loadPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_cpu_load',
      );
  late final _system_cpu_load = _system_cpu_loadPtr
      .asFunction<double Function(ffi.Pointer<YseSystem>)>();

  /// Convenience.
  void system_sleep(ffi.Pointer<YseSystem> sys, int ms) {
    return _system_sleep(sys, ms);
  }

  late final _system_sleepPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSystem>, ffi.UnsignedInt)
        >
      >('yse_system_sleep');
  late final _system_sleep = _system_sleepPtr
      .asFunction<void Function(ffi.Pointer<YseSystem>, int)>();

  /// Settings.
  void system_set_max_sounds(ffi.Pointer<YseSystem> sys, int value) {
    return _system_set_max_sounds(sys, value);
  }

  late final _system_set_max_soundsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>, ffi.Int)>
      >('yse_system_set_max_sounds');
  late final _system_set_max_sounds = _system_set_max_soundsPtr
      .asFunction<void Function(ffi.Pointer<YseSystem>, int)>();

  int system_get_max_sounds(ffi.Pointer<YseSystem> sys) {
    return _system_get_max_sounds(sys);
  }

  late final _system_get_max_soundsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSystem>)>>(
        'yse_system_get_max_sounds',
      );
  late final _system_get_max_sounds = _system_get_max_soundsPtr
      .asFunction<int Function(ffi.Pointer<YseSystem>)>();

  void system_audio_test(ffi.Pointer<YseSystem> sys, int on) {
    return _system_audio_test(sys, on);
  }

  late final _system_audio_testPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSystem>, ffi.Int)>
      >('yse_system_audio_test');
  late final _system_audio_test = _system_audio_testPtr
      .asFunction<void Function(ffi.Pointer<YseSystem>, int)>();

  void system_auto_reconnect(ffi.Pointer<YseSystem> sys, int on, int delay_ms) {
    return _system_auto_reconnect(sys, on, delay_ms);
  }

  late final _system_auto_reconnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSystem>, ffi.Int, ffi.Int)
        >
      >('yse_system_auto_reconnect');
  late final _system_auto_reconnect = _system_auto_reconnectPtr
      .asFunction<void Function(ffi.Pointer<YseSystem>, int, int)>();

  /// Borrowed singleton pointer — never destroy.
  ffi.Pointer<YseListener> listener_get() {
    return _listener_get();
  }

  late final _listener_getPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseListener> Function()>>(
        'yse_listener_get',
      );
  late final _listener_get = _listener_getPtr
      .asFunction<ffi.Pointer<YseListener> Function()>();

  void listener_set_pos(ffi.Pointer<YseListener> l, ffi.Pointer<yse_pos_t> p) {
    return _listener_set_pos(l, p);
  }

  late final _listener_set_posPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseListener>, ffi.Pointer<yse_pos_t>)
        >
      >('yse_listener_set_pos');
  late final _listener_set_pos = _listener_set_posPtr
      .asFunction<
        void Function(ffi.Pointer<YseListener>, ffi.Pointer<yse_pos_t>)
      >();

  yse_pos_t listener_get_pos(ffi.Pointer<YseListener> l) {
    return _listener_get_pos(l);
  }

  late final _listener_get_posPtr =
      _lookup<ffi.NativeFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>>(
        'yse_listener_get_pos',
      );
  late final _listener_get_pos = _listener_get_posPtr
      .asFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>();

  yse_pos_t listener_get_vel(ffi.Pointer<YseListener> l) {
    return _listener_get_vel(l);
  }

  late final _listener_get_velPtr =
      _lookup<ffi.NativeFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>>(
        'yse_listener_get_vel',
      );
  late final _listener_get_vel = _listener_get_velPtr
      .asFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>();

  yse_pos_t listener_get_forward(ffi.Pointer<YseListener> l) {
    return _listener_get_forward(l);
  }

  late final _listener_get_forwardPtr =
      _lookup<ffi.NativeFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>>(
        'yse_listener_get_forward',
      );
  late final _listener_get_forward = _listener_get_forwardPtr
      .asFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>();

  yse_pos_t listener_get_upward(ffi.Pointer<YseListener> l) {
    return _listener_get_upward(l);
  }

  late final _listener_get_upwardPtr =
      _lookup<ffi.NativeFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>>(
        'yse_listener_get_upward',
      );
  late final _listener_get_upward = _listener_get_upwardPtr
      .asFunction<yse_pos_t Function(ffi.Pointer<YseListener>)>();

  void listener_set_orient(
    ffi.Pointer<YseListener> l,
    ffi.Pointer<yse_pos_t> forward,
    ffi.Pointer<yse_pos_t> up,
  ) {
    return _listener_set_orient(l, forward, up);
  }

  late final _listener_set_orientPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<YseListener>,
            ffi.Pointer<yse_pos_t>,
            ffi.Pointer<yse_pos_t>,
          )
        >
      >('yse_listener_set_orient');
  late final _listener_set_orient = _listener_set_orientPtr
      .asFunction<
        void Function(
          ffi.Pointer<YseListener>,
          ffi.Pointer<yse_pos_t>,
          ffi.Pointer<yse_pos_t>,
        )
      >();

  /// Pre-built channels — borrowed pointers, never destroy.
  ffi.Pointer<YseChannel> channel_master() {
    return _channel_master();
  }

  late final _channel_masterPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_master',
      );
  late final _channel_master = _channel_masterPtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  ffi.Pointer<YseChannel> channel_fx() {
    return _channel_fx();
  }

  late final _channel_fxPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_fx',
      );
  late final _channel_fx = _channel_fxPtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  ffi.Pointer<YseChannel> channel_music() {
    return _channel_music();
  }

  late final _channel_musicPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_music',
      );
  late final _channel_music = _channel_musicPtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  ffi.Pointer<YseChannel> channel_ambient() {
    return _channel_ambient();
  }

  late final _channel_ambientPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_ambient',
      );
  late final _channel_ambient = _channel_ambientPtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  ffi.Pointer<YseChannel> channel_voice() {
    return _channel_voice();
  }

  late final _channel_voicePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_voice',
      );
  late final _channel_voice = _channel_voicePtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  ffi.Pointer<YseChannel> channel_gui() {
    return _channel_gui();
  }

  late final _channel_guiPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseChannel> Function()>>(
        'yse_channel_gui',
      );
  late final _channel_gui = _channel_guiPtr
      .asFunction<ffi.Pointer<YseChannel> Function()>();

  /// User-created channels.
  ffi.Pointer<YseChannel> channel_create(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<YseChannel> parent,
  ) {
    return _channel_create(name, parent);
  }

  late final _channel_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<YseChannel> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<YseChannel>,
          )
        >
      >('yse_channel_create');
  late final _channel_create = _channel_createPtr
      .asFunction<
        ffi.Pointer<YseChannel> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<YseChannel>,
        )
      >();

  void channel_destroy(ffi.Pointer<YseChannel> ch) {
    return _channel_destroy(ch);
  }

  late final _channel_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseChannel>)>>(
        'yse_channel_destroy',
      );
  late final _channel_destroy = _channel_destroyPtr
      .asFunction<void Function(ffi.Pointer<YseChannel>)>();

  void channel_set_volume(ffi.Pointer<YseChannel> ch, double value) {
    return _channel_set_volume(ch, value);
  }

  late final _channel_set_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseChannel>, ffi.Float)
        >
      >('yse_channel_set_volume');
  late final _channel_set_volume = _channel_set_volumePtr
      .asFunction<void Function(ffi.Pointer<YseChannel>, double)>();

  double channel_get_volume(ffi.Pointer<YseChannel> ch) {
    return _channel_get_volume(ch);
  }

  late final _channel_get_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseChannel>)>>(
        'yse_channel_get_volume',
      );
  late final _channel_get_volume = _channel_get_volumePtr
      .asFunction<double Function(ffi.Pointer<YseChannel>)>();

  void channel_move_to(
    ffi.Pointer<YseChannel> ch,
    ffi.Pointer<YseChannel> parent,
  ) {
    return _channel_move_to(ch, parent);
  }

  late final _channel_move_toPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseChannel>, ffi.Pointer<YseChannel>)
        >
      >('yse_channel_move_to');
  late final _channel_move_to = _channel_move_toPtr
      .asFunction<
        void Function(ffi.Pointer<YseChannel>, ffi.Pointer<YseChannel>)
      >();

  void channel_attach_reverb(ffi.Pointer<YseChannel> ch) {
    return _channel_attach_reverb(ch);
  }

  late final _channel_attach_reverbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseChannel>)>>(
        'yse_channel_attach_reverb',
      );
  late final _channel_attach_reverb = _channel_attach_reverbPtr
      .asFunction<void Function(ffi.Pointer<YseChannel>)>();

  void channel_set_virtual(ffi.Pointer<YseChannel> ch, int value) {
    return _channel_set_virtual(ch, value);
  }

  late final _channel_set_virtualPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseChannel>, ffi.Int)>
      >('yse_channel_set_virtual');
  late final _channel_set_virtual = _channel_set_virtualPtr
      .asFunction<void Function(ffi.Pointer<YseChannel>, int)>();

  int channel_get_virtual(ffi.Pointer<YseChannel> ch) {
    return _channel_get_virtual(ch);
  }

  late final _channel_get_virtualPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseChannel>)>>(
        'yse_channel_get_virtual',
      );
  late final _channel_get_virtual = _channel_get_virtualPtr
      .asFunction<int Function(ffi.Pointer<YseChannel>)>();

  int channel_is_valid(ffi.Pointer<YseChannel> ch) {
    return _channel_is_valid(ch);
  }

  late final _channel_is_validPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseChannel>)>>(
        'yse_channel_is_valid',
      );
  late final _channel_is_valid = _channel_is_validPtr
      .asFunction<int Function(ffi.Pointer<YseChannel>)>();

  ffi.Pointer<ffi.Char> channel_get_name(ffi.Pointer<YseChannel> ch) {
    return _channel_get_name(ch);
  }

  late final _channel_get_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<YseChannel>)
        >
      >('yse_channel_get_name');
  late final _channel_get_name = _channel_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<YseChannel>)>();

  ffi.Pointer<YseSound> sound_create() {
    return _sound_create();
  }

  late final _sound_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<YseSound> Function()>>(
        'yse_sound_create',
      );
  late final _sound_create = _sound_createPtr
      .asFunction<ffi.Pointer<YseSound> Function()>();

  void sound_destroy(ffi.Pointer<YseSound> s) {
    return _sound_destroy(s);
  }

  late final _sound_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_destroy',
      );
  late final _sound_destroy = _sound_destroyPtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  /// Initialize a sound from a file on disk. Must be called once after
  /// yse_sound_create() and before any other method.
  YseStatus sound_load_file(
    ffi.Pointer<YseSound> s,
    ffi.Pointer<ffi.Char> filename,
    ffi.Pointer<YseChannel> ch,
    int loop,
    double volume,
    int streaming,
  ) {
    return YseStatus.fromValue(
      _sound_load_file(s, filename, ch, loop, volume, streaming),
    );
  }

  late final _sound_load_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<YseSound>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<YseChannel>,
            ffi.Int,
            ffi.Float,
            ffi.Int,
          )
        >
      >('yse_sound_load_file');
  late final _sound_load_file = _sound_load_filePtr
      .asFunction<
        int Function(
          ffi.Pointer<YseSound>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<YseChannel>,
          int,
          double,
          int,
        )
      >();

  int sound_is_valid(ffi.Pointer<YseSound> s) {
    return _sound_is_valid(s);
  }

  late final _sound_is_validPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_valid',
      );
  late final _sound_is_valid = _sound_is_validPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  int sound_is_ready(ffi.Pointer<YseSound> s) {
    return _sound_is_ready(s);
  }

  late final _sound_is_readyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_ready',
      );
  late final _sound_is_ready = _sound_is_readyPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  int sound_is_streaming(ffi.Pointer<YseSound> s) {
    return _sound_is_streaming(s);
  }

  late final _sound_is_streamingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_streaming',
      );
  late final _sound_is_streaming = _sound_is_streamingPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  /// Transport.
  void sound_play(ffi.Pointer<YseSound> s) {
    return _sound_play(s);
  }

  late final _sound_playPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_play',
      );
  late final _sound_play = _sound_playPtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  void sound_pause(ffi.Pointer<YseSound> s) {
    return _sound_pause(s);
  }

  late final _sound_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_pause',
      );
  late final _sound_pause = _sound_pausePtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  void sound_stop(ffi.Pointer<YseSound> s) {
    return _sound_stop(s);
  }

  late final _sound_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_stop',
      );
  late final _sound_stop = _sound_stopPtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  void sound_toggle(ffi.Pointer<YseSound> s) {
    return _sound_toggle(s);
  }

  late final _sound_togglePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_toggle',
      );
  late final _sound_toggle = _sound_togglePtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  void sound_restart(ffi.Pointer<YseSound> s) {
    return _sound_restart(s);
  }

  late final _sound_restartPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_restart',
      );
  late final _sound_restart = _sound_restartPtr
      .asFunction<void Function(ffi.Pointer<YseSound>)>();

  int sound_is_playing(ffi.Pointer<YseSound> s) {
    return _sound_is_playing(s);
  }

  late final _sound_is_playingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_playing',
      );
  late final _sound_is_playing = _sound_is_playingPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  int sound_is_paused(ffi.Pointer<YseSound> s) {
    return _sound_is_paused(s);
  }

  late final _sound_is_pausedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_paused',
      );
  late final _sound_is_paused = _sound_is_pausedPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  int sound_is_stopped(ffi.Pointer<YseSound> s) {
    return _sound_is_stopped(s);
  }

  late final _sound_is_stoppedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_is_stopped',
      );
  late final _sound_is_stopped = _sound_is_stoppedPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  /// 3D + mixing.
  void sound_set_pos(ffi.Pointer<YseSound> s, ffi.Pointer<yse_pos_t> p) {
    return _sound_set_pos(s, p);
  }

  late final _sound_set_posPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSound>, ffi.Pointer<yse_pos_t>)
        >
      >('yse_sound_set_pos');
  late final _sound_set_pos = _sound_set_posPtr
      .asFunction<
        void Function(ffi.Pointer<YseSound>, ffi.Pointer<yse_pos_t>)
      >();

  yse_pos_t sound_get_pos(ffi.Pointer<YseSound> s) {
    return _sound_get_pos(s);
  }

  late final _sound_get_posPtr =
      _lookup<ffi.NativeFunction<yse_pos_t Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_pos',
      );
  late final _sound_get_pos = _sound_get_posPtr
      .asFunction<yse_pos_t Function(ffi.Pointer<YseSound>)>();

  void sound_set_volume(ffi.Pointer<YseSound> s, double v, int fade_ms) {
    return _sound_set_volume(s, v, fade_ms);
  }

  late final _sound_set_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSound>, ffi.Float, ffi.UnsignedInt)
        >
      >('yse_sound_set_volume');
  late final _sound_set_volume = _sound_set_volumePtr
      .asFunction<void Function(ffi.Pointer<YseSound>, double, int)>();

  double sound_get_volume(ffi.Pointer<YseSound> s) {
    return _sound_get_volume(s);
  }

  late final _sound_get_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_volume',
      );
  late final _sound_get_volume = _sound_get_volumePtr
      .asFunction<double Function(ffi.Pointer<YseSound>)>();

  void sound_set_speed(ffi.Pointer<YseSound> s, double v) {
    return _sound_set_speed(s, v);
  }

  late final _sound_set_speedPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Float)>
      >('yse_sound_set_speed');
  late final _sound_set_speed = _sound_set_speedPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, double)>();

  double sound_get_speed(ffi.Pointer<YseSound> s) {
    return _sound_get_speed(s);
  }

  late final _sound_get_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_speed',
      );
  late final _sound_get_speed = _sound_get_speedPtr
      .asFunction<double Function(ffi.Pointer<YseSound>)>();

  void sound_set_size(ffi.Pointer<YseSound> s, double v) {
    return _sound_set_size(s, v);
  }

  late final _sound_set_sizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Float)>
      >('yse_sound_set_size');
  late final _sound_set_size = _sound_set_sizePtr
      .asFunction<void Function(ffi.Pointer<YseSound>, double)>();

  double sound_get_size(ffi.Pointer<YseSound> s) {
    return _sound_get_size(s);
  }

  late final _sound_get_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_size',
      );
  late final _sound_get_size = _sound_get_sizePtr
      .asFunction<double Function(ffi.Pointer<YseSound>)>();

  void sound_set_spread(ffi.Pointer<YseSound> s, double v) {
    return _sound_set_spread(s, v);
  }

  late final _sound_set_spreadPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Float)>
      >('yse_sound_set_spread');
  late final _sound_set_spread = _sound_set_spreadPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, double)>();

  double sound_get_spread(ffi.Pointer<YseSound> s) {
    return _sound_get_spread(s);
  }

  late final _sound_get_spreadPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_spread',
      );
  late final _sound_get_spread = _sound_get_spreadPtr
      .asFunction<double Function(ffi.Pointer<YseSound>)>();

  void sound_set_looping(ffi.Pointer<YseSound> s, int v) {
    return _sound_set_looping(s, v);
  }

  late final _sound_set_loopingPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Int)>
      >('yse_sound_set_looping');
  late final _sound_set_looping = _sound_set_loopingPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  int sound_get_looping(ffi.Pointer<YseSound> s) {
    return _sound_get_looping(s);
  }

  late final _sound_get_loopingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_looping',
      );
  late final _sound_get_looping = _sound_get_loopingPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_set_relative(ffi.Pointer<YseSound> s, int v) {
    return _sound_set_relative(s, v);
  }

  late final _sound_set_relativePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Int)>
      >('yse_sound_set_relative');
  late final _sound_set_relative = _sound_set_relativePtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  int sound_get_relative(ffi.Pointer<YseSound> s) {
    return _sound_get_relative(s);
  }

  late final _sound_get_relativePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_relative',
      );
  late final _sound_get_relative = _sound_get_relativePtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_set_doppler(ffi.Pointer<YseSound> s, int v) {
    return _sound_set_doppler(s, v);
  }

  late final _sound_set_dopplerPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Int)>
      >('yse_sound_set_doppler');
  late final _sound_set_doppler = _sound_set_dopplerPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  int sound_get_doppler(ffi.Pointer<YseSound> s) {
    return _sound_get_doppler(s);
  }

  late final _sound_get_dopplerPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_doppler',
      );
  late final _sound_get_doppler = _sound_get_dopplerPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_set_pan2d(ffi.Pointer<YseSound> s, int v) {
    return _sound_set_pan2d(s, v);
  }

  late final _sound_set_pan2dPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Int)>
      >('yse_sound_set_pan2d');
  late final _sound_set_pan2d = _sound_set_pan2dPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  int sound_get_pan2d(ffi.Pointer<YseSound> s) {
    return _sound_get_pan2d(s);
  }

  late final _sound_get_pan2dPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_pan2d',
      );
  late final _sound_get_pan2d = _sound_get_pan2dPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_set_occlusion(ffi.Pointer<YseSound> s, int v) {
    return _sound_set_occlusion(s, v);
  }

  late final _sound_set_occlusionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Int)>
      >('yse_sound_set_occlusion');
  late final _sound_set_occlusion = _sound_set_occlusionPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  int sound_get_occlusion(ffi.Pointer<YseSound> s) {
    return _sound_get_occlusion(s);
  }

  late final _sound_get_occlusionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_occlusion',
      );
  late final _sound_get_occlusion = _sound_get_occlusionPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_fade_and_stop(ffi.Pointer<YseSound> s, int time_ms) {
    return _sound_fade_and_stop(s, time_ms);
  }

  late final _sound_fade_and_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSound>, ffi.UnsignedInt)
        >
      >('yse_sound_fade_and_stop');
  late final _sound_fade_and_stop = _sound_fade_and_stopPtr
      .asFunction<void Function(ffi.Pointer<YseSound>, int)>();

  /// Playhead.
  void sound_set_time(ffi.Pointer<YseSound> s, double samples) {
    return _sound_set_time(s, samples);
  }

  late final _sound_set_timePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>, ffi.Float)>
      >('yse_sound_set_time');
  late final _sound_set_time = _sound_set_timePtr
      .asFunction<void Function(ffi.Pointer<YseSound>, double)>();

  double sound_get_time(ffi.Pointer<YseSound> s) {
    return _sound_get_time(s);
  }

  late final _sound_get_timePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<YseSound>)>>(
        'yse_sound_get_time',
      );
  late final _sound_get_time = _sound_get_timePtr
      .asFunction<double Function(ffi.Pointer<YseSound>)>();

  int sound_length(ffi.Pointer<YseSound> s) {
    return _sound_length(s);
  }

  late final _sound_lengthPtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<YseSound>)>
      >('yse_sound_length');
  late final _sound_length = _sound_lengthPtr
      .asFunction<int Function(ffi.Pointer<YseSound>)>();

  void sound_move_to(ffi.Pointer<YseSound> s, ffi.Pointer<YseChannel> target) {
    return _sound_move_to(s, target);
  }

  late final _sound_move_toPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<YseSound>, ffi.Pointer<YseChannel>)
        >
      >('yse_sound_move_to');
  late final _sound_move_to = _sound_move_toPtr
      .asFunction<
        void Function(ffi.Pointer<YseSound>, ffi.Pointer<YseChannel>)
      >();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final YseBindings _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseChannel>)>>
  get channel_destroy => _library._channel_destroyPtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<YseSound>)>>
  get sound_destroy => _library._sound_destroyPtr;
}

enum YseStatus {
  YSE_OK(0),
  YSE_ERR_GENERIC(1),
  YSE_ERR_NOT_INITIALIZED(2),
  YSE_ERR_INVALID_HANDLE(3),
  YSE_ERR_INVALID_ARGUMENT(4),
  YSE_ERR_FILE_NOT_FOUND(5),
  YSE_ERR_AUDIO_DEVICE(6),
  YSE_ERR_MIDI(7),
  YSE_ERR_EXCEPTION(8);

  final int value;
  const YseStatus(this.value);

  static YseStatus fromValue(int value) => switch (value) {
    0 => YSE_OK,
    1 => YSE_ERR_GENERIC,
    2 => YSE_ERR_NOT_INITIALIZED,
    3 => YSE_ERR_INVALID_HANDLE,
    4 => YSE_ERR_INVALID_ARGUMENT,
    5 => YSE_ERR_FILE_NOT_FOUND,
    6 => YSE_ERR_AUDIO_DEVICE,
    7 => YSE_ERR_MIDI,
    8 => YSE_ERR_EXCEPTION,
    _ => throw ArgumentError('Unknown value for YseStatus: $value'),
  };
}

final class yse_pos_t extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double z;
}

/// Mirrors YSE::CHANNEL_TYPE in headers/enums.hpp.
enum YseChannelType {
  YSE_CT_AUTO(0),
  YSE_CT_MONO(1),
  YSE_CT_STEREO(2),
  YSE_CT_QUAD(3),
  YSE_CT_51(4),
  YSE_CT_51SIDE(5),
  YSE_CT_61(6),
  YSE_CT_71(7),
  YSE_CT_CUSTOM(8);

  final int value;
  const YseChannelType(this.value);

  static YseChannelType fromValue(int value) => switch (value) {
    0 => YSE_CT_AUTO,
    1 => YSE_CT_MONO,
    2 => YSE_CT_STEREO,
    3 => YSE_CT_QUAD,
    4 => YSE_CT_51,
    5 => YSE_CT_51SIDE,
    6 => YSE_CT_61,
    7 => YSE_CT_71,
    8 => YSE_CT_CUSTOM,
    _ => throw ArgumentError('Unknown value for YseChannelType: $value'),
  };
}

final class YseSystem extends ffi.Opaque {}

final class YseListener extends ffi.Opaque {}

final class YseChannel extends ffi.Opaque {}

final class YseSound extends ffi.Opaque {}
